apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmchart-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helmchart-controller
  template:
    metadata:
      labels:
        name: helmchart-controller
    spec:
      serviceAccountName: helmchart-controller
      containers:
        - name: helmchart-controller
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - helmchart-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "helmchart-controller"
